language: python
sudo: false
cache: false
python:
    - '3.6'
os:
    - linux
    - osx
env:
  global:
    PYTHONUNBUFFERED=yes
  matrix:
    - TOXENV=3.6
    - TOXENV=flake8
    - TOXENV=typecheck
    - TOXENV=apicheck
install: travis_retry pip install -U tox
script: tox -v -- -v
