version: "2"

services:
  db:
    container_name: quiver_db
    environment:
      POSTGRES_DB: quiver
      POSTGRES_USER: quiver
      POSTGRES_PASSWORD: password
    image: postgres:9.5
    ports:
      - "5432:5432"
